# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Type Check

on:
  push:
    branches: [ "main", "develop" ] # Thêm nhánh develop
  pull_request:
    branches: [ "main", "develop" ] # Thêm nhánh develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 24.x, 25.x] 

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci 
      # 'npm ci' tốt hơn 'npm install' cho CI vì nó cài chính xác theo package-lock.json

      # Bước 1: Check cú pháp code (ESLint) - Clean code trước đã
    - name: Lint Code
      run: npm run lint

    - name: Build Project
      run: npm run build
      # Bước này check xem code có build được ra file production không

    # - run: npm test 
    # Tạm thời comment dòng test lại nếu dự án chưa viết test, để đỡ bị báo lỗi đỏ oan
